required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: -33
  y: -59
  z: 10
  yaw: 90
  pitch: 3.3
arenas:
  0:
    world: 'world'
    x: -45
    y: -59
    z: 16
    yaw: 90
    pitch: 3.3
  1:
    world: 'world'
    x: -45
    y: -59
    z: 1
    yaw: 90
    pitch: 3.3